CREATE TABLE kb_docs (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2(200),
    texto CLOB,
    embedding VECTOR(384, FLOAT32)
);

INSERT INTO kb_docs (titulo, texto)
VALUES (
'Governança de Dados',
'Governança de Dados é o conjunto de políticas, processos, papéis e responsabilidades que ajudam uma organização a usar seus dados com qualidade, segurança e confiança.'
);

INSERT INTO kb_docs (titulo, texto)
VALUES (
'Qualidade de Dados',
'Qualidade de Dados envolve garantir que os dados estejam corretos, completos, consistentes, atualizados e adequados para apoiar decisões.'
);

INSERT INTO kb_docs (titulo, texto)
VALUES (
'Master Data Management',
'MDM, ou Master Data Management, é a prática de organizar e padronizar os dados principais de uma organização, como clientes, produtos, fornecedores e unidades.'
);

INSERT INTO kb_docs (titulo, texto)
VALUES (
'Data Warehouse',
'Data Warehouse é um ambiente centralizado que reúne dados históricos de várias fontes para apoiar análises, relatórios e tomada de decisão.'
);

INSERT INTO kb_docs (titulo, texto)
VALUES (
'LGPD',
'A LGPD é a Lei Geral de Proteção de Dados, que define regras para coleta, armazenamento, tratamento e compartilhamento de dados pessoais no Brasil.'
);

INSERT INTO kb_docs (titulo, texto)
VALUES (
'ETL',
'ETL significa extração, transformação e carga de dados. É o processo utilizado para coletar dados de diferentes fontes, tratar essas informações e carregá-las em um destino, como um Data Warehouse.'
);

INSERT INTO kb_docs (titulo, texto)
VALUES (
'Metadados',
'Metadados são dados que descrevem outros dados. Eles ajudam a entender origem, significado, formato, responsável e regras de uso de uma informação.'
);

INSERT INTO kb_docs (titulo, texto)
VALUES (
'Catálogo de Dados',
'Catálogo de Dados é uma ferramenta usada para organizar, documentar e facilitar a descoberta dos dados disponíveis em uma organização.'
);

COMMIT;

INSERT INTO kb_docs (titulo, texto)
VALUES (
'Diferença entre Governança e MDM',
'Governança de Dados define políticas e responsabilidades. MDM é responsável pela gestão e padronização dos dados mestres da organização.'
);

INSERT INTO kb_docs (titulo, texto)
VALUES (
'Objetivo do Data Warehouse',
'Um Data Warehouse é utilizado para consolidar dados históricos e apoiar análises estratégicas e tomadas de decisão.'
);

INSERT INTO kb_docs (titulo, texto)
VALUES (
'Importância da Qualidade de Dados',
'Dados incorretos podem gerar decisões erradas, prejuízos financeiros e problemas regulatórios.'
);

INSERT INTO kb_docs (titulo, texto)
VALUES (
'Exemplo de Metadados',
'Nome da coluna, tipo de dado, data de criação e responsável pela informação são exemplos de metadados.'
);