package main

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"os"
	"strconv"
	"strings"
	"time"

	_ "github.com/sijms/go-ora/v2"
)

/*
DDL didatico para criar a tabela no Oracle Free Full 23ai.

Conectar no DBeaver ou SQL*Plus usando:
- Host: localhost
- Port: 1522
- Service Name: FREEPDB1
- User: system
- Password: OraclePwd123

CREATE TABLE modelos_llms (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR2(120) NOT NULL,
  input_token_limit NUMBER NOT NULL,
  output_token_limit NUMBER NOT NULL,
  provider VARCHAR2(80) DEFAULT 'openai' NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

Exemplo de insert manual:

INSERT INTO modelos_llms (nome, input_token_limit, output_token_limit, provider)
VALUES ('gpt-5.4', 200000, 128000, 'openai');

COMMIT;

Exemplos de chamadas HTTP:

GET /api/v1/llm
GET /api/v1/llm?id=1

curl -X POST http://localhost:8080/api/v1/llm \
  -H 'Content-Type: application/json' \
  -d '{"nome":"gpt-5.4","input_token_limit":200000,"output_token_limit":128000,"provider":"openai"}'

curl -X PUT 'http://localhost:8080/api/v1/llm?id=1' \
  -H 'Content-Type: application/json' \
  -d '{"nome":"gpt-5.4-mini","input_token_limit":128000,"output_token_limit":64000,"provider":"openai"}'

curl -X DELETE 'http://localhost:8080/api/v1/llm?id=1'
*/

type LLMModel struct {
	ID               int64     `json:"id"`
	Nome             string    `json:"nome"`
	InputTokenLimit  int64     `json:"input_token_limit"`
	OutputTokenLimit int64     `json:"output_token_limit"`
	Provider         string    `json:"provider"`
	CreatedAt        time.Time `json:"created_at"`
}

type createLLMRequest struct {
	Nome             string `json:"nome"`
	InputTokenLimit  int64  `json:"input_token_limit"`
	OutputTokenLimit int64  `json:"output_token_limit"`
	Provider         string `json:"provider"`
}

type updateLLMRequest struct {
	Nome             string `json:"nome"`
	InputTokenLimit  int64  `json:"input_token_limit"`
	OutputTokenLimit int64  `json:"output_token_limit"`
	Provider         string `json:"provider"`
}

type errorResponse struct {
	Error string `json:"error"`
}

type app struct {
	db     *sql.DB
	logger *slog.Logger
}

func main() {
	logger := slog.New(slog.NewTextHandler(os.Stdout, &slog.HandlerOptions{Level: slog.LevelInfo}))

	dsn := env("ORACLE_DSN", "oracle://system:OraclePwd123@localhost:1522/FREEPDB1")
	addr := env("HTTP_ADDR", ":8080")

	db, err := sql.Open("oracle", dsn)
	if err != nil {
		logger.Error("erro ao abrir conexao oracle", "error", err)
		os.Exit(1)
	}
	defer db.Close()

	db.SetMaxOpenConns(5)
	db.SetMaxIdleConns(5)
	db.SetConnMaxLifetime(30 * time.Minute)

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	if err := db.PingContext(ctx); err != nil {
		logger.Error("erro ao conectar no oracle", "error", err)
		os.Exit(1)
	}

	application := &app{db: db, logger: logger}

	mux := http.NewServeMux()
	mux.HandleFunc("GET /health", application.handleHealth)
	mux.HandleFunc("GET /api/v1/llm", application.handleGetLLMs)
	mux.HandleFunc("POST /api/v1/llm", application.handleCreateLLM)
	mux.HandleFunc("PUT /api/v1/llm", application.handleUpdateLLM)
	mux.HandleFunc("DELETE /api/v1/llm", application.handleDeleteLLM)

	logger.Info("oracle conectado", "dsn", dsn)
	printEndpoints(addr)
	if err := http.ListenAndServe(addr, mux); err != nil {
		logger.Error("erro ao iniciar servidor http", "error", err)
		os.Exit(1)
	}
}

func printEndpoints(addr string) {
	fmt.Println("Servidor HTTP iniciado em", addr)
	fmt.Println("Endpoints disponíveis:")
	fmt.Println("  GET    /health")
	fmt.Println("  GET    /api/v1/llm")
	fmt.Println("  GET    /api/v1/llm?id=1")
	fmt.Println("  POST   /api/v1/llm")
	fmt.Println("  PUT    /api/v1/llm?id=1")
	fmt.Println("  DELETE /api/v1/llm?id=1")
}

func (a *app) handleHealth(w http.ResponseWriter, r *http.Request) {
	ctx, cancel := context.WithTimeout(r.Context(), 3*time.Second)
	defer cancel()
	if err := a.db.PingContext(ctx); err != nil {
		a.logger.Warn("healthcheck falhou", "error", err)
		writeError(w, http.StatusServiceUnavailable, err.Error())
		return
	}

	writeJSON(w, http.StatusOK, map[string]string{"status": "ok"})
}

func (a *app) handleGetLLMs(w http.ResponseWriter, r *http.Request) {
	id, hasID, err := parseOptionalID(r)
	if err != nil {
		writeError(w, http.StatusBadRequest, err.Error())
		return
	}

	ctx, cancel := context.WithTimeout(r.Context(), 5*time.Second)
	defer cancel()

	if hasID {
		a.logger.Info("buscando modelo llm", "id", id)
		model, err := a.findLLMByID(ctx, id)
		if err != nil {
			if errors.Is(err, sql.ErrNoRows) {
				writeError(w, http.StatusNotFound, "modelo llm nao encontrado")
				return
			}
			writeError(w, http.StatusInternalServerError, err.Error())
			return
		}
		writeJSON(w, http.StatusOK, model)
		return
	}

	a.logger.Info("listando modelos llm")

	rows, err := a.db.QueryContext(ctx, `
		SELECT id, nome, input_token_limit, output_token_limit, provider, created_at
		FROM modelos_llms
		ORDER BY id`)
	if err != nil {
		writeError(w, http.StatusInternalServerError, err.Error())
		return
	}
	defer rows.Close()

	models := make([]LLMModel, 0)
	for rows.Next() {
		model, err := scanLLM(rows)
		if err != nil {
			writeError(w, http.StatusInternalServerError, err.Error())
			return
		}
		models = append(models, model)
	}
	if err := rows.Err(); err != nil {
		writeError(w, http.StatusInternalServerError, err.Error())
		return
	}

	writeJSON(w, http.StatusOK, models)
}

func (a *app) handleCreateLLM(w http.ResponseWriter, r *http.Request) {
	var input createLLMRequest
	if err := readJSON(r, &input); err != nil {
		writeError(w, http.StatusBadRequest, err.Error())
		return
	}
	if err := validateLLMInput(input.Nome, input.InputTokenLimit, input.OutputTokenLimit); err != nil {
		writeError(w, http.StatusBadRequest, err.Error())
		return
	}
	if strings.TrimSpace(input.Provider) == "" {
		input.Provider = "openai"
	}

	ctx, cancel := context.WithTimeout(r.Context(), 5*time.Second)
	defer cancel()

	a.logger.Info("criando modelo llm", "nome", input.Nome, "provider", input.Provider)

	var id int64
	_, err := a.db.ExecContext(ctx, `
		INSERT INTO modelos_llms (nome, input_token_limit, output_token_limit, provider)
		VALUES (:1, :2, :3, :4)
		RETURNING id INTO :5`,
		input.Nome,
		input.InputTokenLimit,
		input.OutputTokenLimit,
		input.Provider,
		sql.Out{Dest: &id},
	)
	if err != nil {
		writeError(w, http.StatusInternalServerError, err.Error())
		return
	}

	model, err := a.findLLMByID(ctx, id)
	if err != nil {
		writeError(w, http.StatusInternalServerError, err.Error())
		return
	}

	writeJSON(w, http.StatusCreated, model)
}

func (a *app) handleUpdateLLM(w http.ResponseWriter, r *http.Request) {
	id, err := parseRequiredID(r)
	if err != nil {
		writeError(w, http.StatusBadRequest, err.Error())
		return
	}

	var input updateLLMRequest
	if err := readJSON(r, &input); err != nil {
		writeError(w, http.StatusBadRequest, err.Error())
		return
	}
	if err := validateLLMInput(input.Nome, input.InputTokenLimit, input.OutputTokenLimit); err != nil {
		writeError(w, http.StatusBadRequest, err.Error())
		return
	}
	if strings.TrimSpace(input.Provider) == "" {
		input.Provider = "openai"
	}

	ctx, cancel := context.WithTimeout(r.Context(), 5*time.Second)
	defer cancel()

	a.logger.Info("atualizando modelo llm", "id", id, "nome", input.Nome)

	result, err := a.db.ExecContext(ctx, `
		UPDATE modelos_llms
		SET nome = :1,
		    input_token_limit = :2,
		    output_token_limit = :3,
		    provider = :4
		WHERE id = :5`,
		input.Nome,
		input.InputTokenLimit,
		input.OutputTokenLimit,
		input.Provider,
		id,
	)
	if err != nil {
		writeError(w, http.StatusInternalServerError, err.Error())
		return
	}

	affected, _ := result.RowsAffected()
	if affected == 0 {
		writeError(w, http.StatusNotFound, "modelo llm nao encontrado")
		return
	}

	model, err := a.findLLMByID(ctx, id)
	if err != nil {
		writeError(w, http.StatusInternalServerError, err.Error())
		return
	}

	writeJSON(w, http.StatusOK, model)
}

func (a *app) handleDeleteLLM(w http.ResponseWriter, r *http.Request) {
	id, err := parseRequiredID(r)
	if err != nil {
		writeError(w, http.StatusBadRequest, err.Error())
		return
	}

	ctx, cancel := context.WithTimeout(r.Context(), 5*time.Second)
	defer cancel()

	a.logger.Info("removendo modelo llm", "id", id)

	result, err := a.db.ExecContext(ctx, `DELETE FROM modelos_llms WHERE id = :1`, id)
	if err != nil {
		writeError(w, http.StatusInternalServerError, err.Error())
		return
	}

	affected, _ := result.RowsAffected()
	if affected == 0 {
		writeError(w, http.StatusNotFound, "modelo llm nao encontrado")
		return
	}

	writeJSON(w, http.StatusOK, map[string]any{"deleted": true, "id": id})
}

func (a *app) findLLMByID(ctx context.Context, id int64) (LLMModel, error) {
	row := a.db.QueryRowContext(ctx, `
		SELECT id, nome, input_token_limit, output_token_limit, provider, created_at
		FROM modelos_llms
		WHERE id = :1`, id)
	return scanLLM(row)
}

type llmScanner interface {
	Scan(dest ...any) error
}

func scanLLM(scanner llmScanner) (LLMModel, error) {
	var model LLMModel
	err := scanner.Scan(
		&model.ID,
		&model.Nome,
		&model.InputTokenLimit,
		&model.OutputTokenLimit,
		&model.Provider,
		&model.CreatedAt,
	)
	return model, err
}

func parseOptionalID(r *http.Request) (int64, bool, error) {
	value := strings.TrimSpace(r.URL.Query().Get("id"))
	if value == "" {
		return 0, false, nil
	}
	id, err := strconv.ParseInt(value, 10, 64)
	if err != nil || id <= 0 {
		return 0, false, fmt.Errorf("query param id deve ser um numero positivo")
	}
	return id, true, nil
}

func parseRequiredID(r *http.Request) (int64, error) {
	id, hasID, err := parseOptionalID(r)
	if err != nil {
		return 0, err
	}
	if !hasID {
		return 0, fmt.Errorf("query param id e obrigatorio")
	}
	return id, nil
}

func validateLLMInput(nome string, inputTokenLimit int64, outputTokenLimit int64) error {
	if strings.TrimSpace(nome) == "" {
		return fmt.Errorf("nome e obrigatorio")
	}
	if inputTokenLimit <= 0 {
		return fmt.Errorf("input_token_limit deve ser maior que zero")
	}
	if outputTokenLimit <= 0 {
		return fmt.Errorf("output_token_limit deve ser maior que zero")
	}
	return nil
}

func readJSON(r *http.Request, dest any) error {
	defer r.Body.Close()
	decoder := json.NewDecoder(r.Body)
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(dest); err != nil {
		return err
	}
	return nil
}

func writeJSON(w http.ResponseWriter, status int, value any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(value)
}

func writeError(w http.ResponseWriter, status int, message string) {
	writeJSON(w, status, errorResponse{Error: message})
}

func env(key string, fallback string) string {
	value := strings.TrimSpace(os.Getenv(key))
	if value == "" {
		return fallback
	}
	return value
}
