FROM golang:1.26 AS builder

WORKDIR /app

COPY go.mod .
COPY main.go .

RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o /go-server .

FROM gcr.io/distroless/static-debian12:nonroot

COPY --from=builder /go-server /go-server

EXPOSE 8080

ENTRYPOINT ["/go-server"]
