FROM golang:1.26-alpine AS builder

WORKDIR /app

COPY go.mod .
COPY main.go .

RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o /go-server .

FROM scratch

COPY --from=builder /go-server /go-server

EXPOSE 8080

ENTRYPOINT ["/go-server"]
