FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod .
COPY main.go .

RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o /go-server .

FROM alpine:3.20

WORKDIR /app

COPY --from=builder /go-server /app/go-server

RUN adduser -D -H appuser

USER appuser

EXPOSE 8080

CMD ["/app/go-server"]
