WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
SET ECHO ON
SET FEEDBACK ON
SET HEADING ON
SET PAGESIZE 50
SET LINESIZE 160

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE produtos_carga PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE produtos PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

CREATE TABLE produtos (
  id_produto   NUMBER PRIMARY KEY,
  nome_produto VARCHAR2(100) NOT NULL,
  categoria    VARCHAR2(50) NOT NULL,
  preco        NUMBER(10, 2) NOT NULL,
  criado_em    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ck_produtos_preco CHECK (preco >= 0)
);

CREATE TABLE produtos_carga (
  id_produto   NUMBER PRIMARY KEY,
  nome_produto VARCHAR2(100) NOT NULL,
  categoria    VARCHAR2(50) NOT NULL,
  preco        NUMBER(10, 2) NOT NULL,
  CONSTRAINT ck_produtos_carga_preco CHECK (preco >= 0)
);

INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (1, 'Produto 0001', 'Software', 11.37);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (2, 'Produto 0002', 'Servicos', 12.74);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (3, 'Produto 0003', 'Acessorios', 14.11);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (4, 'Produto 0004', 'Hardware', 15.48);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (5, 'Produto 0005', 'Software', 16.85);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (6, 'Produto 0006', 'Servicos', 18.22);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (7, 'Produto 0007', 'Acessorios', 19.59);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (8, 'Produto 0008', 'Hardware', 20.96);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (9, 'Produto 0009', 'Software', 22.33);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (10, 'Produto 0010', 'Servicos', 23.70);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (11, 'Produto 0011', 'Acessorios', 25.07);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (12, 'Produto 0012', 'Hardware', 26.44);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (13, 'Produto 0013', 'Software', 27.81);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (14, 'Produto 0014', 'Servicos', 29.18);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (15, 'Produto 0015', 'Acessorios', 30.55);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (16, 'Produto 0016', 'Hardware', 31.92);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (17, 'Produto 0017', 'Software', 33.29);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (18, 'Produto 0018', 'Servicos', 34.66);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (19, 'Produto 0019', 'Acessorios', 36.03);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (20, 'Produto 0020', 'Hardware', 37.40);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (21, 'Produto 0021', 'Software', 38.77);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (22, 'Produto 0022', 'Servicos', 40.14);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (23, 'Produto 0023', 'Acessorios', 41.51);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (24, 'Produto 0024', 'Hardware', 42.88);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (25, 'Produto 0025', 'Software', 44.25);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (26, 'Produto 0026', 'Servicos', 45.62);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (27, 'Produto 0027', 'Acessorios', 46.99);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (28, 'Produto 0028', 'Hardware', 48.36);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (29, 'Produto 0029', 'Software', 49.73);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (30, 'Produto 0030', 'Servicos', 51.10);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (31, 'Produto 0031', 'Acessorios', 52.47);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (32, 'Produto 0032', 'Hardware', 53.84);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (33, 'Produto 0033', 'Software', 55.21);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (34, 'Produto 0034', 'Servicos', 56.58);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (35, 'Produto 0035', 'Acessorios', 57.95);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (36, 'Produto 0036', 'Hardware', 59.32);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (37, 'Produto 0037', 'Software', 60.69);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (38, 'Produto 0038', 'Servicos', 62.06);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (39, 'Produto 0039', 'Acessorios', 63.43);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (40, 'Produto 0040', 'Hardware', 64.80);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (41, 'Produto 0041', 'Software', 66.17);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (42, 'Produto 0042', 'Servicos', 67.54);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (43, 'Produto 0043', 'Acessorios', 68.91);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (44, 'Produto 0044', 'Hardware', 70.28);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (45, 'Produto 0045', 'Software', 71.65);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (46, 'Produto 0046', 'Servicos', 73.02);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (47, 'Produto 0047', 'Acessorios', 74.39);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (48, 'Produto 0048', 'Hardware', 75.76);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (49, 'Produto 0049', 'Software', 77.13);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (50, 'Produto 0050', 'Servicos', 78.50);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (51, 'Produto 0051', 'Acessorios', 79.87);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (52, 'Produto 0052', 'Hardware', 81.24);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (53, 'Produto 0053', 'Software', 82.61);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (54, 'Produto 0054', 'Servicos', 83.98);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (55, 'Produto 0055', 'Acessorios', 85.35);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (56, 'Produto 0056', 'Hardware', 86.72);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (57, 'Produto 0057', 'Software', 88.09);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (58, 'Produto 0058', 'Servicos', 89.46);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (59, 'Produto 0059', 'Acessorios', 90.83);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (60, 'Produto 0060', 'Hardware', 92.20);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (61, 'Produto 0061', 'Software', 93.57);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (62, 'Produto 0062', 'Servicos', 94.94);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (63, 'Produto 0063', 'Acessorios', 96.31);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (64, 'Produto 0064', 'Hardware', 97.68);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (65, 'Produto 0065', 'Software', 99.05);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (66, 'Produto 0066', 'Servicos', 100.42);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (67, 'Produto 0067', 'Acessorios', 101.79);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (68, 'Produto 0068', 'Hardware', 103.16);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (69, 'Produto 0069', 'Software', 104.53);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (70, 'Produto 0070', 'Servicos', 105.90);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (71, 'Produto 0071', 'Acessorios', 107.27);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (72, 'Produto 0072', 'Hardware', 108.64);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (73, 'Produto 0073', 'Software', 110.01);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (74, 'Produto 0074', 'Servicos', 111.38);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (75, 'Produto 0075', 'Acessorios', 112.75);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (76, 'Produto 0076', 'Hardware', 114.12);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (77, 'Produto 0077', 'Software', 115.49);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (78, 'Produto 0078', 'Servicos', 116.86);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (79, 'Produto 0079', 'Acessorios', 118.23);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (80, 'Produto 0080', 'Hardware', 119.60);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (81, 'Produto 0081', 'Software', 120.97);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (82, 'Produto 0082', 'Servicos', 122.34);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (83, 'Produto 0083', 'Acessorios', 123.71);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (84, 'Produto 0084', 'Hardware', 125.08);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (85, 'Produto 0085', 'Software', 126.45);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (86, 'Produto 0086', 'Servicos', 127.82);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (87, 'Produto 0087', 'Acessorios', 129.19);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (88, 'Produto 0088', 'Hardware', 130.56);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (89, 'Produto 0089', 'Software', 131.93);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (90, 'Produto 0090', 'Servicos', 133.30);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (91, 'Produto 0091', 'Acessorios', 134.67);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (92, 'Produto 0092', 'Hardware', 136.04);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (93, 'Produto 0093', 'Software', 137.41);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (94, 'Produto 0094', 'Servicos', 138.78);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (95, 'Produto 0095', 'Acessorios', 140.15);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (96, 'Produto 0096', 'Hardware', 141.52);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (97, 'Produto 0097', 'Software', 142.89);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (98, 'Produto 0098', 'Servicos', 144.26);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (99, 'Produto 0099', 'Acessorios', 145.63);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (100, 'Produto 0100', 'Hardware', 147.00);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (101, 'Produto 0101', 'Software', 148.37);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (102, 'Produto 0102', 'Servicos', 149.74);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (103, 'Produto 0103', 'Acessorios', 151.11);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (104, 'Produto 0104', 'Hardware', 152.48);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (105, 'Produto 0105', 'Software', 153.85);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (106, 'Produto 0106', 'Servicos', 155.22);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (107, 'Produto 0107', 'Acessorios', 156.59);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (108, 'Produto 0108', 'Hardware', 157.96);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (109, 'Produto 0109', 'Software', 159.33);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (110, 'Produto 0110', 'Servicos', 160.70);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (111, 'Produto 0111', 'Acessorios', 162.07);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (112, 'Produto 0112', 'Hardware', 163.44);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (113, 'Produto 0113', 'Software', 164.81);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (114, 'Produto 0114', 'Servicos', 166.18);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (115, 'Produto 0115', 'Acessorios', 167.55);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (116, 'Produto 0116', 'Hardware', 168.92);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (117, 'Produto 0117', 'Software', 170.29);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (118, 'Produto 0118', 'Servicos', 171.66);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (119, 'Produto 0119', 'Acessorios', 173.03);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (120, 'Produto 0120', 'Hardware', 174.40);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (121, 'Produto 0121', 'Software', 175.77);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (122, 'Produto 0122', 'Servicos', 177.14);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (123, 'Produto 0123', 'Acessorios', 178.51);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (124, 'Produto 0124', 'Hardware', 179.88);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (125, 'Produto 0125', 'Software', 181.25);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (126, 'Produto 0126', 'Servicos', 182.62);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (127, 'Produto 0127', 'Acessorios', 183.99);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (128, 'Produto 0128', 'Hardware', 185.36);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (129, 'Produto 0129', 'Software', 186.73);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (130, 'Produto 0130', 'Servicos', 188.10);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (131, 'Produto 0131', 'Acessorios', 189.47);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (132, 'Produto 0132', 'Hardware', 190.84);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (133, 'Produto 0133', 'Software', 192.21);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (134, 'Produto 0134', 'Servicos', 193.58);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (135, 'Produto 0135', 'Acessorios', 194.95);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (136, 'Produto 0136', 'Hardware', 196.32);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (137, 'Produto 0137', 'Software', 197.69);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (138, 'Produto 0138', 'Servicos', 199.06);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (139, 'Produto 0139', 'Acessorios', 200.43);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (140, 'Produto 0140', 'Hardware', 201.80);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (141, 'Produto 0141', 'Software', 203.17);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (142, 'Produto 0142', 'Servicos', 204.54);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (143, 'Produto 0143', 'Acessorios', 205.91);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (144, 'Produto 0144', 'Hardware', 207.28);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (145, 'Produto 0145', 'Software', 208.65);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (146, 'Produto 0146', 'Servicos', 210.02);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (147, 'Produto 0147', 'Acessorios', 211.39);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (148, 'Produto 0148', 'Hardware', 212.76);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (149, 'Produto 0149', 'Software', 214.13);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (150, 'Produto 0150', 'Servicos', 215.50);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (151, 'Produto 0151', 'Acessorios', 216.87);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (152, 'Produto 0152', 'Hardware', 218.24);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (153, 'Produto 0153', 'Software', 219.61);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (154, 'Produto 0154', 'Servicos', 220.98);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (155, 'Produto 0155', 'Acessorios', 222.35);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (156, 'Produto 0156', 'Hardware', 223.72);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (157, 'Produto 0157', 'Software', 225.09);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (158, 'Produto 0158', 'Servicos', 226.46);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (159, 'Produto 0159', 'Acessorios', 227.83);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (160, 'Produto 0160', 'Hardware', 229.20);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (161, 'Produto 0161', 'Software', 230.57);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (162, 'Produto 0162', 'Servicos', 231.94);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (163, 'Produto 0163', 'Acessorios', 233.31);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (164, 'Produto 0164', 'Hardware', 234.68);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (165, 'Produto 0165', 'Software', 236.05);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (166, 'Produto 0166', 'Servicos', 237.42);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (167, 'Produto 0167', 'Acessorios', 238.79);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (168, 'Produto 0168', 'Hardware', 240.16);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (169, 'Produto 0169', 'Software', 241.53);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (170, 'Produto 0170', 'Servicos', 242.90);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (171, 'Produto 0171', 'Acessorios', 244.27);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (172, 'Produto 0172', 'Hardware', 245.64);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (173, 'Produto 0173', 'Software', 247.01);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (174, 'Produto 0174', 'Servicos', 248.38);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (175, 'Produto 0175', 'Acessorios', 249.75);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (176, 'Produto 0176', 'Hardware', 251.12);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (177, 'Produto 0177', 'Software', 252.49);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (178, 'Produto 0178', 'Servicos', 253.86);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (179, 'Produto 0179', 'Acessorios', 255.23);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (180, 'Produto 0180', 'Hardware', 256.60);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (181, 'Produto 0181', 'Software', 257.97);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (182, 'Produto 0182', 'Servicos', 259.34);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (183, 'Produto 0183', 'Acessorios', 260.71);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (184, 'Produto 0184', 'Hardware', 262.08);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (185, 'Produto 0185', 'Software', 263.45);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (186, 'Produto 0186', 'Servicos', 264.82);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (187, 'Produto 0187', 'Acessorios', 266.19);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (188, 'Produto 0188', 'Hardware', 267.56);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (189, 'Produto 0189', 'Software', 268.93);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (190, 'Produto 0190', 'Servicos', 270.30);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (191, 'Produto 0191', 'Acessorios', 271.67);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (192, 'Produto 0192', 'Hardware', 273.04);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (193, 'Produto 0193', 'Software', 274.41);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (194, 'Produto 0194', 'Servicos', 275.78);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (195, 'Produto 0195', 'Acessorios', 277.15);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (196, 'Produto 0196', 'Hardware', 278.52);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (197, 'Produto 0197', 'Software', 279.89);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (198, 'Produto 0198', 'Servicos', 281.26);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (199, 'Produto 0199', 'Acessorios', 282.63);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (200, 'Produto 0200', 'Hardware', 284.00);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (201, 'Produto 0201', 'Software', 285.37);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (202, 'Produto 0202', 'Servicos', 286.74);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (203, 'Produto 0203', 'Acessorios', 288.11);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (204, 'Produto 0204', 'Hardware', 289.48);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (205, 'Produto 0205', 'Software', 290.85);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (206, 'Produto 0206', 'Servicos', 292.22);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (207, 'Produto 0207', 'Acessorios', 293.59);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (208, 'Produto 0208', 'Hardware', 294.96);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (209, 'Produto 0209', 'Software', 296.33);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (210, 'Produto 0210', 'Servicos', 297.70);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (211, 'Produto 0211', 'Acessorios', 299.07);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (212, 'Produto 0212', 'Hardware', 300.44);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (213, 'Produto 0213', 'Software', 301.81);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (214, 'Produto 0214', 'Servicos', 303.18);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (215, 'Produto 0215', 'Acessorios', 304.55);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (216, 'Produto 0216', 'Hardware', 305.92);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (217, 'Produto 0217', 'Software', 307.29);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (218, 'Produto 0218', 'Servicos', 308.66);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (219, 'Produto 0219', 'Acessorios', 310.03);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (220, 'Produto 0220', 'Hardware', 311.40);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (221, 'Produto 0221', 'Software', 312.77);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (222, 'Produto 0222', 'Servicos', 314.14);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (223, 'Produto 0223', 'Acessorios', 315.51);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (224, 'Produto 0224', 'Hardware', 316.88);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (225, 'Produto 0225', 'Software', 318.25);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (226, 'Produto 0226', 'Servicos', 319.62);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (227, 'Produto 0227', 'Acessorios', 320.99);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (228, 'Produto 0228', 'Hardware', 322.36);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (229, 'Produto 0229', 'Software', 323.73);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (230, 'Produto 0230', 'Servicos', 325.10);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (231, 'Produto 0231', 'Acessorios', 326.47);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (232, 'Produto 0232', 'Hardware', 327.84);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (233, 'Produto 0233', 'Software', 329.21);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (234, 'Produto 0234', 'Servicos', 330.58);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (235, 'Produto 0235', 'Acessorios', 331.95);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (236, 'Produto 0236', 'Hardware', 333.32);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (237, 'Produto 0237', 'Software', 334.69);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (238, 'Produto 0238', 'Servicos', 336.06);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (239, 'Produto 0239', 'Acessorios', 337.43);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (240, 'Produto 0240', 'Hardware', 338.80);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (241, 'Produto 0241', 'Software', 340.17);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (242, 'Produto 0242', 'Servicos', 341.54);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (243, 'Produto 0243', 'Acessorios', 342.91);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (244, 'Produto 0244', 'Hardware', 344.28);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (245, 'Produto 0245', 'Software', 345.65);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (246, 'Produto 0246', 'Servicos', 347.02);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (247, 'Produto 0247', 'Acessorios', 348.39);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (248, 'Produto 0248', 'Hardware', 349.76);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (249, 'Produto 0249', 'Software', 351.13);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (250, 'Produto 0250', 'Servicos', 352.50);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (251, 'Produto 0251', 'Acessorios', 353.87);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (252, 'Produto 0252', 'Hardware', 355.24);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (253, 'Produto 0253', 'Software', 356.61);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (254, 'Produto 0254', 'Servicos', 357.98);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (255, 'Produto 0255', 'Acessorios', 359.35);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (256, 'Produto 0256', 'Hardware', 360.72);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (257, 'Produto 0257', 'Software', 362.09);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (258, 'Produto 0258', 'Servicos', 363.46);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (259, 'Produto 0259', 'Acessorios', 364.83);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (260, 'Produto 0260', 'Hardware', 366.20);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (261, 'Produto 0261', 'Software', 367.57);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (262, 'Produto 0262', 'Servicos', 368.94);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (263, 'Produto 0263', 'Acessorios', 370.31);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (264, 'Produto 0264', 'Hardware', 371.68);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (265, 'Produto 0265', 'Software', 373.05);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (266, 'Produto 0266', 'Servicos', 374.42);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (267, 'Produto 0267', 'Acessorios', 375.79);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (268, 'Produto 0268', 'Hardware', 377.16);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (269, 'Produto 0269', 'Software', 378.53);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (270, 'Produto 0270', 'Servicos', 379.90);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (271, 'Produto 0271', 'Acessorios', 381.27);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (272, 'Produto 0272', 'Hardware', 382.64);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (273, 'Produto 0273', 'Software', 384.01);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (274, 'Produto 0274', 'Servicos', 385.38);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (275, 'Produto 0275', 'Acessorios', 386.75);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (276, 'Produto 0276', 'Hardware', 388.12);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (277, 'Produto 0277', 'Software', 389.49);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (278, 'Produto 0278', 'Servicos', 390.86);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (279, 'Produto 0279', 'Acessorios', 392.23);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (280, 'Produto 0280', 'Hardware', 393.60);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (281, 'Produto 0281', 'Software', 394.97);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (282, 'Produto 0282', 'Servicos', 396.34);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (283, 'Produto 0283', 'Acessorios', 397.71);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (284, 'Produto 0284', 'Hardware', 399.08);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (285, 'Produto 0285', 'Software', 400.45);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (286, 'Produto 0286', 'Servicos', 401.82);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (287, 'Produto 0287', 'Acessorios', 403.19);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (288, 'Produto 0288', 'Hardware', 404.56);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (289, 'Produto 0289', 'Software', 405.93);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (290, 'Produto 0290', 'Servicos', 407.30);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (291, 'Produto 0291', 'Acessorios', 408.67);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (292, 'Produto 0292', 'Hardware', 410.04);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (293, 'Produto 0293', 'Software', 411.41);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (294, 'Produto 0294', 'Servicos', 412.78);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (295, 'Produto 0295', 'Acessorios', 414.15);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (296, 'Produto 0296', 'Hardware', 415.52);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (297, 'Produto 0297', 'Software', 416.89);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (298, 'Produto 0298', 'Servicos', 418.26);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (299, 'Produto 0299', 'Acessorios', 419.63);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (300, 'Produto 0300', 'Hardware', 421.00);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (301, 'Produto 0301', 'Software', 422.37);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (302, 'Produto 0302', 'Servicos', 423.74);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (303, 'Produto 0303', 'Acessorios', 425.11);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (304, 'Produto 0304', 'Hardware', 426.48);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (305, 'Produto 0305', 'Software', 427.85);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (306, 'Produto 0306', 'Servicos', 429.22);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (307, 'Produto 0307', 'Acessorios', 430.59);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (308, 'Produto 0308', 'Hardware', 431.96);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (309, 'Produto 0309', 'Software', 433.33);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (310, 'Produto 0310', 'Servicos', 434.70);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (311, 'Produto 0311', 'Acessorios', 436.07);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (312, 'Produto 0312', 'Hardware', 437.44);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (313, 'Produto 0313', 'Software', 438.81);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (314, 'Produto 0314', 'Servicos', 440.18);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (315, 'Produto 0315', 'Acessorios', 441.55);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (316, 'Produto 0316', 'Hardware', 442.92);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (317, 'Produto 0317', 'Software', 444.29);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (318, 'Produto 0318', 'Servicos', 445.66);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (319, 'Produto 0319', 'Acessorios', 447.03);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (320, 'Produto 0320', 'Hardware', 448.40);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (321, 'Produto 0321', 'Software', 449.77);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (322, 'Produto 0322', 'Servicos', 451.14);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (323, 'Produto 0323', 'Acessorios', 452.51);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (324, 'Produto 0324', 'Hardware', 453.88);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (325, 'Produto 0325', 'Software', 455.25);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (326, 'Produto 0326', 'Servicos', 456.62);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (327, 'Produto 0327', 'Acessorios', 457.99);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (328, 'Produto 0328', 'Hardware', 459.36);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (329, 'Produto 0329', 'Software', 460.73);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (330, 'Produto 0330', 'Servicos', 462.10);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (331, 'Produto 0331', 'Acessorios', 463.47);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (332, 'Produto 0332', 'Hardware', 464.84);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (333, 'Produto 0333', 'Software', 466.21);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (334, 'Produto 0334', 'Servicos', 467.58);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (335, 'Produto 0335', 'Acessorios', 468.95);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (336, 'Produto 0336', 'Hardware', 470.32);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (337, 'Produto 0337', 'Software', 471.69);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (338, 'Produto 0338', 'Servicos', 473.06);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (339, 'Produto 0339', 'Acessorios', 474.43);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (340, 'Produto 0340', 'Hardware', 475.80);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (341, 'Produto 0341', 'Software', 477.17);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (342, 'Produto 0342', 'Servicos', 478.54);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (343, 'Produto 0343', 'Acessorios', 479.91);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (344, 'Produto 0344', 'Hardware', 481.28);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (345, 'Produto 0345', 'Software', 482.65);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (346, 'Produto 0346', 'Servicos', 484.02);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (347, 'Produto 0347', 'Acessorios', 485.39);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (348, 'Produto 0348', 'Hardware', 486.76);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (349, 'Produto 0349', 'Software', 488.13);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (350, 'Produto 0350', 'Servicos', 489.50);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (351, 'Produto 0351', 'Acessorios', 490.87);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (352, 'Produto 0352', 'Hardware', 492.24);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (353, 'Produto 0353', 'Software', 493.61);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (354, 'Produto 0354', 'Servicos', 494.98);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (355, 'Produto 0355', 'Acessorios', 496.35);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (356, 'Produto 0356', 'Hardware', 497.72);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (357, 'Produto 0357', 'Software', 499.09);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (358, 'Produto 0358', 'Servicos', 500.46);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (359, 'Produto 0359', 'Acessorios', 501.83);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (360, 'Produto 0360', 'Hardware', 503.20);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (361, 'Produto 0361', 'Software', 504.57);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (362, 'Produto 0362', 'Servicos', 505.94);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (363, 'Produto 0363', 'Acessorios', 507.31);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (364, 'Produto 0364', 'Hardware', 508.68);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (365, 'Produto 0365', 'Software', 510.05);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (366, 'Produto 0366', 'Servicos', 511.42);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (367, 'Produto 0367', 'Acessorios', 512.79);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (368, 'Produto 0368', 'Hardware', 514.16);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (369, 'Produto 0369', 'Software', 515.53);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (370, 'Produto 0370', 'Servicos', 516.90);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (371, 'Produto 0371', 'Acessorios', 518.27);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (372, 'Produto 0372', 'Hardware', 519.64);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (373, 'Produto 0373', 'Software', 521.01);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (374, 'Produto 0374', 'Servicos', 522.38);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (375, 'Produto 0375', 'Acessorios', 523.75);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (376, 'Produto 0376', 'Hardware', 525.12);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (377, 'Produto 0377', 'Software', 526.49);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (378, 'Produto 0378', 'Servicos', 527.86);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (379, 'Produto 0379', 'Acessorios', 529.23);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (380, 'Produto 0380', 'Hardware', 530.60);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (381, 'Produto 0381', 'Software', 531.97);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (382, 'Produto 0382', 'Servicos', 533.34);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (383, 'Produto 0383', 'Acessorios', 534.71);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (384, 'Produto 0384', 'Hardware', 536.08);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (385, 'Produto 0385', 'Software', 537.45);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (386, 'Produto 0386', 'Servicos', 538.82);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (387, 'Produto 0387', 'Acessorios', 540.19);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (388, 'Produto 0388', 'Hardware', 541.56);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (389, 'Produto 0389', 'Software', 542.93);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (390, 'Produto 0390', 'Servicos', 544.30);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (391, 'Produto 0391', 'Acessorios', 545.67);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (392, 'Produto 0392', 'Hardware', 547.04);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (393, 'Produto 0393', 'Software', 548.41);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (394, 'Produto 0394', 'Servicos', 549.78);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (395, 'Produto 0395', 'Acessorios', 551.15);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (396, 'Produto 0396', 'Hardware', 552.52);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (397, 'Produto 0397', 'Software', 553.89);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (398, 'Produto 0398', 'Servicos', 555.26);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (399, 'Produto 0399', 'Acessorios', 556.63);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (400, 'Produto 0400', 'Hardware', 558.00);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (401, 'Produto 0401', 'Software', 559.37);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (402, 'Produto 0402', 'Servicos', 560.74);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (403, 'Produto 0403', 'Acessorios', 562.11);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (404, 'Produto 0404', 'Hardware', 563.48);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (405, 'Produto 0405', 'Software', 564.85);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (406, 'Produto 0406', 'Servicos', 566.22);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (407, 'Produto 0407', 'Acessorios', 567.59);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (408, 'Produto 0408', 'Hardware', 568.96);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (409, 'Produto 0409', 'Software', 570.33);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (410, 'Produto 0410', 'Servicos', 571.70);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (411, 'Produto 0411', 'Acessorios', 573.07);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (412, 'Produto 0412', 'Hardware', 574.44);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (413, 'Produto 0413', 'Software', 575.81);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (414, 'Produto 0414', 'Servicos', 577.18);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (415, 'Produto 0415', 'Acessorios', 578.55);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (416, 'Produto 0416', 'Hardware', 579.92);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (417, 'Produto 0417', 'Software', 581.29);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (418, 'Produto 0418', 'Servicos', 582.66);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (419, 'Produto 0419', 'Acessorios', 584.03);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (420, 'Produto 0420', 'Hardware', 585.40);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (421, 'Produto 0421', 'Software', 586.77);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (422, 'Produto 0422', 'Servicos', 588.14);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (423, 'Produto 0423', 'Acessorios', 589.51);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (424, 'Produto 0424', 'Hardware', 590.88);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (425, 'Produto 0425', 'Software', 592.25);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (426, 'Produto 0426', 'Servicos', 593.62);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (427, 'Produto 0427', 'Acessorios', 594.99);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (428, 'Produto 0428', 'Hardware', 596.36);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (429, 'Produto 0429', 'Software', 597.73);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (430, 'Produto 0430', 'Servicos', 599.10);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (431, 'Produto 0431', 'Acessorios', 600.47);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (432, 'Produto 0432', 'Hardware', 601.84);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (433, 'Produto 0433', 'Software', 603.21);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (434, 'Produto 0434', 'Servicos', 604.58);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (435, 'Produto 0435', 'Acessorios', 605.95);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (436, 'Produto 0436', 'Hardware', 607.32);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (437, 'Produto 0437', 'Software', 608.69);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (438, 'Produto 0438', 'Servicos', 610.06);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (439, 'Produto 0439', 'Acessorios', 611.43);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (440, 'Produto 0440', 'Hardware', 612.80);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (441, 'Produto 0441', 'Software', 614.17);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (442, 'Produto 0442', 'Servicos', 615.54);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (443, 'Produto 0443', 'Acessorios', 616.91);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (444, 'Produto 0444', 'Hardware', 618.28);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (445, 'Produto 0445', 'Software', 619.65);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (446, 'Produto 0446', 'Servicos', 621.02);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (447, 'Produto 0447', 'Acessorios', 622.39);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (448, 'Produto 0448', 'Hardware', 623.76);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (449, 'Produto 0449', 'Software', 625.13);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (450, 'Produto 0450', 'Servicos', 626.50);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (451, 'Produto 0451', 'Acessorios', 627.87);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (452, 'Produto 0452', 'Hardware', 629.24);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (453, 'Produto 0453', 'Software', 630.61);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (454, 'Produto 0454', 'Servicos', 631.98);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (455, 'Produto 0455', 'Acessorios', 633.35);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (456, 'Produto 0456', 'Hardware', 634.72);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (457, 'Produto 0457', 'Software', 636.09);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (458, 'Produto 0458', 'Servicos', 637.46);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (459, 'Produto 0459', 'Acessorios', 638.83);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (460, 'Produto 0460', 'Hardware', 640.20);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (461, 'Produto 0461', 'Software', 641.57);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (462, 'Produto 0462', 'Servicos', 642.94);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (463, 'Produto 0463', 'Acessorios', 644.31);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (464, 'Produto 0464', 'Hardware', 645.68);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (465, 'Produto 0465', 'Software', 647.05);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (466, 'Produto 0466', 'Servicos', 648.42);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (467, 'Produto 0467', 'Acessorios', 649.79);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (468, 'Produto 0468', 'Hardware', 651.16);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (469, 'Produto 0469', 'Software', 652.53);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (470, 'Produto 0470', 'Servicos', 653.90);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (471, 'Produto 0471', 'Acessorios', 655.27);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (472, 'Produto 0472', 'Hardware', 656.64);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (473, 'Produto 0473', 'Software', 658.01);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (474, 'Produto 0474', 'Servicos', 659.38);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (475, 'Produto 0475', 'Acessorios', 660.75);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (476, 'Produto 0476', 'Hardware', 662.12);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (477, 'Produto 0477', 'Software', 663.49);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (478, 'Produto 0478', 'Servicos', 664.86);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (479, 'Produto 0479', 'Acessorios', 666.23);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (480, 'Produto 0480', 'Hardware', 667.60);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (481, 'Produto 0481', 'Software', 668.97);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (482, 'Produto 0482', 'Servicos', 670.34);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (483, 'Produto 0483', 'Acessorios', 671.71);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (484, 'Produto 0484', 'Hardware', 673.08);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (485, 'Produto 0485', 'Software', 674.45);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (486, 'Produto 0486', 'Servicos', 675.82);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (487, 'Produto 0487', 'Acessorios', 677.19);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (488, 'Produto 0488', 'Hardware', 678.56);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (489, 'Produto 0489', 'Software', 679.93);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (490, 'Produto 0490', 'Servicos', 681.30);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (491, 'Produto 0491', 'Acessorios', 682.67);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (492, 'Produto 0492', 'Hardware', 684.04);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (493, 'Produto 0493', 'Software', 685.41);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (494, 'Produto 0494', 'Servicos', 686.78);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (495, 'Produto 0495', 'Acessorios', 688.15);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (496, 'Produto 0496', 'Hardware', 689.52);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (497, 'Produto 0497', 'Software', 690.89);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (498, 'Produto 0498', 'Servicos', 692.26);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (499, 'Produto 0499', 'Acessorios', 693.63);
INSERT INTO produtos (id_produto, nome_produto, categoria, preco) VALUES (500, 'Produto 0500', 'Hardware', 695.00);

COMMIT;

SELECT COUNT(*) AS total_produtos
FROM produtos;

SELECT COUNT(*) AS total_produtos_carga
FROM produtos_carga;

EXIT;

