-- abaixo executar com sysdba > docker exec -it oracle-free-full-23ai bash -lc "sqlplus / as sysdba"
ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE USER monitor_app IDENTIFIED BY MonitorApp123
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO monitor_app;
GRANT CREATE TABLE TO monitor_app;
GRANT CREATE VIEW TO monitor_app;
GRANT CREATE PROCEDURE TO monitor_app;
GRANT CREATE SEQUENCE TO monitor_app;
GRANT SELECT ON SYS.V_$INSTANCE TO monitor_app;
GRANT SELECT ON SYS.V_$DATABASE TO monitor_app;
GRANT SELECT ON SYS.V_$SESSION TO monitor_app;
GRANT SELECT ON SYS.V_$SYSTEM_EVENT TO monitor_app;
GRANT SELECT ON SYS.V_$SQLAREA TO monitor_app;
GRANT SELECT ON SYS.V_$PDBS TO monitor_app;
GRANT SELECT ON SYS.V_$SYSSTAT TO monitor_app;
GRANT SELECT ON SYS.DBA_TABLESPACE_USAGE_METRICS TO monitor_app;